### PR TITLE
Added IGRF13 to the project

### LINKED ISSUE #4: Update for IGRF13
IGRF12 is officially expired since 2020-01-01, and warns on every use. The IGRF13 data is available from the usual source, with validity through 2025.

### PR DESCRIPTION
**Pull request by antoinetavant**
Added the fortran file from the website, and updateed the wrapper as well as the project's configurations.

Closes #4 

I may have forgot to update some of the `12` to `13` ....

### CODE REVIEW

**Comment by scivision** [comment]
Thanks for this, I will incorporate this ASAP

**Comment by antoinetavant** [comment]
Actually, after more reflex ion, I'm not sure if updating this package `igrf12` is meaningful.
Maybe the `igrf12` should not incorporate the version 13, and another package `13` should be created.

At least for backward compatibility and clarity...
Anyway, that's just my two cents !

**Comment by scivision** [comment]
Yes I kind of take the Unix philosophy of using an ensemble of tools rather than putting everything in one package. other packages take the kitchen sink approach so I'm just trying to use the complimentary approach.

**Comment by antoinetavant** [comment]
Yes, it make sense !
If you are willing to create the `igrf13` package, I'm open to it, but if you want me to do it I can do it.

**Comment by scivision** [comment]
I forgot to close this, I added IGRF13 some time ago. Thanks!

**Pull request closed without merging**
